[sdl]
fullscreen = false

[dosbox]
machine = vgaonly

[cpu]
cycles = 3000

[autoexec]
mount c /Users/john/Projects/Hobby/espeniasmo/C
c:
cd \espen
\metawndo\mark
set grdev=/e:4
\metawndo\metawndo
advrtnor espen.adv
\metawndo\release
